#!/bin/bash

set -Eeuxo pipefail

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

docker compose build devops \
  && docker compose up -d devops \
  && docker compose exec devops ./docker-entrypoint.sh /bin/bash
