#!/bin/bash

set -Eeuo pipefail

workdir='/app'

PS3='Please select a container: '
IFS=$'\n' read -r -d '' -a docker_containers < <((docker ps --format='{{ .Names }}' | sort -V) && printf '\0')

if [ -z "${docker_containers+x}" ]; then
  echo 'No running containers found'
else
  select container_name in "${docker_containers[@]}"; do
    text="{\"containerName\":\"/${container_name}\"}"
    hex_container_name=$(printf $text | od -A n -t x1 | tr -d '[\n\t]' | tr -d '[:space:]')

    echo 'Starting the editor'
    code --folder-uri="vscode-remote://attached-container+${hex_container_name}${workdir}"
    break
  done
fi
